import CommonMethod from '../../../support/CommonMethod'
/// <reference types="cypress" />
beforeEach(() => {
    CommonMethod.beforeTest()
})
//////////////////////////////Verifying WELL Checklist page fields////////////////////////////////////////////////////
Given('User navigate to the Dashboard page by logging in to wellcertified', function () {
    CommonMethod.loginpage()
    cy.wait(1000)
    cy.xpath(this.locator.projectMenu).click()
    cy.wait(1000)
    cy.xpath(this.locator.PerformanceList.WellPerformance).click()
    cy.get(this.locator.PerformanceList.Applysearch).should('be.visible').click({ force: true })
    cy.wait(2000)
    cy.fixture('performanceId').then(function (getId) {
        this.getId = getId
        cy.get(this.locator.PerformanceList.IDorNamesearch).eq(0).type(this.getId.performanceId)
        cy.wait(2000)
        cy.get(this.locator.PerformanceList.Applysearch).should('be.visible').click({ force: true })
        cy.xpath(this.locator.enrollment.enrollmentStatus).should('contain', 'Registered')
        cy.contains(this.getId.performanceId).click({ force: true })
        cy.wait(2000)
    })
    cy.contains('Checklist').should('be.visible')
})
When('User clicks on Checklist tab', function () {
    cy.wait(4000)
    cy.contains('Checklist').should('be.visible').click({ force: true })
    cy.wait(2000)
})
Then('User redirects to Checklist Page successfully', function () {
    cy.contains('Scorecard').should('be.visible')
    cy.wait(2000)
})
And('User verifies Checklist page fields', function () {
    cy.contains('FEATURE TARGETS (min. 21 required)').should('be.visible')
    cy.xpath(this.locator.Checklist.Searchbtn).should('be.visible')
    cy.xpath(this.locator.Checklist.toggleMetricbtn).should('be.visible')
    cy.xpath(this.locator.Checklist.expandorcollapseRows).should('be.visible')
    cy.xpath(this.locator.Checklist.downloadbtn).should('be.visible')
    cy.wait(4000)
    cy.xpath(this.locator.Checklist.Checklistpart).should('have.length', 36)
})
/////////////////////////////////////Verifying Expand/Collapse Rows in WELLs Checklist page/////////////////////////////////////////////////////////////
Given('User is on WELL Checklist page', function () {
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.Scorecard).scrollIntoView().should('be.visible')
})
When('User clicks on ExpandCollapse Rows button', function () {
    cy.xpath(this.locator.Checklist.expandorcollapseRows).click({ force: true })
    cy.wait(4000)
})
Then('User verifies the expanded rows in Checklist page', function () {
    cy.contains('Meet Thresholds for Particulate Matter').scrollIntoView().should('be.visible')
    cy.xpath(this.locator.Checklist.expandorcollapseRows).click({ force: true })
})
////////////////////////////////////Verifying progress bar by Selecting YES pursue status////////////////////////////////////////////////////////////
When('User verifies the features count by Selecting YES,May Be and No pursue status', function () {
    cy.xpath(this.locator.Checklist.Features).should('contain', '0 Features')
})
Then('User verifies the features count by Selecting YES pursue status', function () {
})
/////////////////////////////Verifying Requirements in Checklist part/////////////////////////////////////////////////////////////////////
When('User clicks on Checklist part', function () {
    cy.contains('Meet Thresholds for Particulate Matter').click({ force: true })
})
Then('User verifies the Requirements fields', function () {
    cy.contains('Requirements').should('be.visible')
    cy.contains('All Spaces except Commercial Kitchen Spaces & Industrial').scrollIntoView().should('be.visible')
    cy.contains('Commercial Kitchen Spaces & Industrial').scrollIntoView().should('be.visible')
    cy.wait(2000)
})
/////////////////////////////Verifying Verification in Checklist part/////////////////////////////////////////////////////////////////////
Given('User navigates to Verification in Checklist part', function () {
    cy.xpath(this.locator.Checklist.checklistverification).scrollIntoView().click({ force: true })
    cy.wait(2000)
})
And('User verifies the Verification fields', function () {
    cy.wait(2000)
    cy.contains('Select an option').scrollIntoView().should('be.visible')
    cy.contains('Assign locations').should('be.visible')
    cy.contains('Upload verification').should('be.visible')
    cy.xpath(this.locator.Checklist.Addoptionbtn).scrollIntoView().should('be.visible')
})
When('User clicks on Add option button', function () {
    cy.xpath(this.locator.Checklist.Addoptionbtn).click({ force: true })
})
And('User Add options by clicking Add button', function () {
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.optionbtn).click({ force: true })
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.exitoption).click({ force: true })
    cy.wait(2000)
})
Then('User verifies the added options', function () {
    cy.contains('Selected Options').scrollIntoView().should('be.visible')
    cy.wait(2000)
})
And('User clicks on Assign locations button', function () {
    cy.xpath(this.locator.Checklist.Assignlocationsbtn).click({ force: true })
    cy.wait(1000)
})
And('User checks the Assign locations checkbox and clicks assign button', function () {
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.locationscheckbox).check()
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.Assignbtn).click({ force: true })
    cy.wait(2000)
})
And('User upload document', function () {
    cy.xpath(this.locator.Checklist.uploadbtn).click({ force: true })
    cy.wait(2000)
    cy.contains('Upload a Document').scrollIntoView().should('be.visible')
    cy.contains('File upload').scrollIntoView().should('be.visible')
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.uploadfilebtn).attachFile(this.data.Uploadfile, { force: true })
    cy.wait(2000)
})
And('User clikcs on Upload button and verifies the uploaded document', function () {
    cy.get(this.locator.Checklist.chklistUploadbtn).contains('Upload').click({ multiple: true })
    cy.wait(7000)
    cy.xpath(this.locator.Checklist.Docstage).scrollIntoView().should('be.visible')
    cy.xpath(this.locator.Checklist.Docreviewstatus).scrollIntoView().should('be.visible')
})
And('User delete the uploaded document', function () {
    cy.xpath(this.locator.Checklist.Docdeletebtn).scrollIntoView().click({ force: true })
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.DocdeleteYesbtn).click({ force: true })
})
And('User verifies No upload documents Message', function () {
    cy.contains('No documents to show').should('be.visible')
})
And('User verifies No upload documents Message', function () {
    cy.contains('No documents to show').should('be.visible')
    cy.wait(1000)
})
And('User edit options', function () {
    cy.xpath(this.locator.Checklist.Editoptionsbtn).click({ force: true })
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.Removeoptionbtn).click({ force: true })
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.removebtn).click({ force: true })
    cy.wait(1000)
})
////////////////////////////////Verifying Comments field//////////////////////////////////////////////////
Given('User navigates to Comments in Checklist part', function () {
    cy.xpath(this.locator.Checklist.checklistcomments).click({ force: true })
    cy.wait(4000)
})
And('User verifies the Add comment fields', function () {
    cy.xpath(this.locator.Checklist.Addcomment).scrollIntoView().should('be.visible')
    cy.xpath(this.locator.Checklist.Postbtn).scrollIntoView().should('be.visible')
})
When('User adds comment', function () {
    cy.xpath(this.locator.Checklist.Addcomment).click({ force: true }).type(this.data.checklist.Addcomment)
})
And('User clicks on post button and verifies the added comment', function () {
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.Postbtn).click({ force: true })
})
And('User delete the comment', function () {
    cy.xpath(this.locator.Checklist.checklistcmntdelete).click({ force: true })
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.cmntdeleteYesbtn).click({ force: true })
})
Then('User verifies deleted comment', function () {
    cy.contains(this.data.checklist.Addcomment).should('not.exist')
    cy.contains('Meet Thresholds for Particulate Matter').click({ force: true })
    cy.wait(2000)
})
///////////////////////////////////////Verifying Resources in Checklist part///////////////////////////////////////////////////////////
Given('User navigates to Resources in Checklist part', function () {
    cy.contains('Meet Thresholds for Particulate Matter').click({ force: true })
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.checklistResources).click({ force: true })
    cy.wait(4000)
})
Then('User verifies the Resources fields', function () {
    cy.contains('There are no resources available for this feature').scrollIntoView().should('be.visible')
    cy.contains('No FAQs available for this feature.').scrollIntoView().should('be.visible')
    cy.contains('Meet Thresholds for Particulate Matter').click({ force: true })
    cy.wait(3000)
})
///////////////////////////////Verifying Search functionality in ALL Concepts///////////////////////////////////////////////
When('User selects Checklist part name in the search field', function () {
    cy.xpath(this.locator.Checklist.Searchbtn).click({ force: true }).type(this.data.checklist.checklistpart, { force: true })
})
Then('User verifies the search result', function () {
    cy.contains("Meet Thresholds for Particulate Matter").should('be.visible')
})
And('User clears the search result', function () {
    cy.xpath(this.locator.Checklist.Searchbtn).click({ force: true }).type(this.data.checklist.checklistpart, { force: true }).clear()
    cy.wait(2000)
})
///////////////////////////////////////////Smoketest//Filling the Checklist for WELL Health Safety////////////////////////////////////////////////////////////////
And('User selects pursue status as YES for 21 features', function () {
    cy.contains('Meet Thresholds for Particulate Matter').should('be.visible')
    cy.wait(2000)
    for (var i = 2; i <= 21; i++) {
        cy.xpath(this.locator.Checklist.pursuestatusYes).click({ force: true })
        cy.wait(3000)
    }
    for (var i = 1; i <= 15; i++) {
        cy.xpath(this.locator.Checklist.pursuestatusNo).click({ force: true })
        cy.wait(3000)
    }
})
And('User verifies the features count after selecting the pursue status', function () {
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.Features).should('contain', '21 Features')
    cy.wait(2000)
})
And('User Add option for Meet Thresholds for Particulate Matter', function () {
    cy.contains('Meet Thresholds for Particulate Matter').click({ force: true })
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.checklistverification).click({ force: true })
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.Addoptionbtn).click({ force: true })
    cy.xpath(this.locator.Checklist.optionbtn).click()
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.exitoption).click()
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.Assignlocationsbtn).click({ force: true })
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.locationscheckbox).check()
    cy.xpath(this.locator.Checklist.Assignbtn).click({ force: true })
    cy.wait(2000)
})
And('User upload document for Meet Thresholds for Particulate Matter', function () {
    cy.xpath(this.locator.Checklist.uploadbtn).click({ force: true })
    cy.wait(2000)
    cy.contains('Upload a Document').scrollIntoView().should('be.visible')
    cy.contains('File upload').scrollIntoView().should('be.visible')
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.uploadfilebtn).attachFile(this.data.Uploadfile, { force: true })
    cy.wait(2000)
    cy.get(this.locator.Checklist.chklistUploadbtn).contains('Upload').click({ multiple: true })
    cy.wait(10000)
    cy.contains('Meet Thresholds for Particulate Matter').click({ force: true })
    cy.wait(1000)
})
And('User Add option for Meet Enhanced Thresholds for Particulate Matter', function () {
    cy.contains('Meet Enhanced Thresholds for Particulate Matter').click({ force: true })
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.checklistverification).click({ force: true })
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.Addoptionbtn).click({ force: true })
    cy.xpath(this.locator.Checklist.optionbtn).click()
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.exitoption).click()
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.Assignlocationsbtn).click({ force: true })
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.locationscheckbox).check()
    cy.xpath(this.locator.Checklist.Assignbtn).click({ force: true })
    cy.wait(2000)
})
And('User upload document for Meet Enhanced Thresholds for Particulate Matter', function () {
    cy.xpath(this.locator.Checklist.uploadbtn).click({ force: true })
    cy.wait(2000)
    cy.contains('Upload a Document').scrollIntoView().should('be.visible')
    cy.contains('File upload').scrollIntoView().should('be.visible')
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.uploadfilebtn).attachFile(this.data.Uploadfile, { force: true })
    cy.wait(2000)
    cy.get(this.locator.Checklist.chklistUploadbtn).contains('Upload').click({ multiple: true })
    cy.wait(10000)
    cy.contains('Meet Enhanced Thresholds for Particulate Matter').click({ force: true })
})
And('User Add option for Meet Thresholds for Organic Gases', function () {
    cy.wait(3000)
    cy.contains('Meet Thresholds for Organic Gases').click({ force: true })
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.checklistverification).click({ force: true })
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.Addoptionbtn).click({ force: true })
    cy.xpath(this.locator.Checklist.PA3optionbtn).click()
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.exitoption).click()
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.Assignlocationsbtn).click({ force: true })
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.locationscheckbox).check()
    cy.xpath(this.locator.Checklist.Assignbtn).click({ force: true })
    cy.wait(2000)
})
And('User upload document for Meet Thresholds for Organic Gases', function () {
    cy.xpath(this.locator.Checklist.uploadbtn).click({ force: true })
    cy.wait(2000)
    cy.contains('Upload a Document').scrollIntoView().should('be.visible')
    cy.contains('File upload').scrollIntoView().should('be.visible')
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.uploadfilebtn).attachFile(this.data.Uploadfile, { force: true })
    cy.wait(2000)
    cy.get(this.locator.Checklist.chklistUploadbtn).contains('Upload').click({ multiple: true })
    cy.wait(10000)
    cy.contains('Meet Thresholds for Organic Gases').click({ force: true })
})
And('User Add option for Meet Enhanced Thresholds for Organic Gases', function () {
    cy.wait(3000)
    cy.contains('Meet Enhanced Thresholds for Organic Gases').click({ force: true })
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.checklistverification).click({ force: true })
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.Addoptionbtn).click({ force: true })
    cy.xpath(this.locator.Checklist.optionbtn).click()
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.exitoption).click()
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.Assignlocationsbtn).click({ force: true })
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.locationscheckbox).check()
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.Assignbtn).click({ force: true })
    cy.wait(2000)
})
And('User upload document for Meet Enhanced Thresholds for Organic Gases', function () {
    cy.xpath(this.locator.Checklist.uploadbtn).click({ force: true })
    cy.wait(2000)
    cy.contains('Upload a Document').scrollIntoView().should('be.visible')
    cy.contains('File upload').scrollIntoView().should('be.visible')
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.uploadfilebtn).attachFile(this.data.Uploadfile, { force: true })
    cy.wait(2000)
    cy.get(this.locator.Checklist.chklistUploadbtn).contains('Upload').click({ multiple: true })
    cy.wait(10000)
    cy.contains('Meet Enhanced Thresholds for Organic Gases').click({ force: true })
})
And('User Add option for Meet Thresholds for Inorganic Gases', function () {
    cy.wait(3000)
    cy.contains('Meet Thresholds for Inorganic Gases').click({ force: true })
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.checklistverification).click({ force: true })
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.Addoptionbtn).click({ force: true })
    cy.xpath(this.locator.Checklist.optionbtn).click()
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.exitoption).click()
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.Assignlocationsbtn).click({ force: true })
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.locationscheckbox).check()
    cy.xpath(this.locator.Checklist.Assignbtn).click({ force: true })
    cy.wait(2000)
})
And('User upload document for Meet Thresholds for Inorganic Gases', function () {
    cy.xpath(this.locator.Checklist.uploadbtn).click({ force: true })
    cy.wait(2000)
    cy.contains('Upload a Document').scrollIntoView().should('be.visible')
    cy.contains('File upload').scrollIntoView().should('be.visible')
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.uploadfilebtn).attachFile(this.data.Uploadfile, { force: true })
    cy.wait(2000)
    cy.get(this.locator.Checklist.chklistUploadbtn).contains('Upload').click({ multiple: true })
    cy.wait(10000)
    cy.contains('Meet Thresholds for Inorganic Gases').click({ force: true })
})
And('User Add option for Meet Enhanced Thresholds for Inorganic Gases', function () {
    cy.wait(3000)
    cy.contains('Meet Enhanced Thresholds for Inorganic Gases').click({ force: true })
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.checklistverification).click({ force: true })
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.Addoptionbtn).click({ force: true })
    cy.xpath(this.locator.Checklist.optionbtn).click()
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.exitoption).click()
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.Assignlocationsbtn).click({ force: true })
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.locationscheckbox).check()
    cy.xpath(this.locator.Checklist.Assignbtn).click({ force: true })
    cy.wait(2000)
})
And('User upload document for Meet Enhanced Thresholds for Inorganic Gases', function () {
    cy.xpath(this.locator.Checklist.uploadbtn).click({ force: true })
    cy.wait(2000)
    cy.contains('Upload a Document').scrollIntoView().should('be.visible')
    cy.contains('File upload').scrollIntoView().should('be.visible')
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.uploadfilebtn).attachFile(this.data.Uploadfile, { force: true })
    cy.wait(2000)
    cy.get(this.locator.Checklist.chklistUploadbtn).contains('Upload').click({ multiple: true })
    cy.wait(10000)
    cy.contains('Meet Enhanced Thresholds for Inorganic Gases').click({ force: true })
})
And('User Add option for Ensure Adequate Ventilation', function () {
    cy.wait(3000)
    cy.contains('Ensure Adequate Ventilation').click({ force: true })
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.checklistverification).click({ force: true })
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.Addoptionbtn).click({ force: true })
    cy.xpath(this.locator.Checklist.optionbtn).click()
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.exitoption).click()
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.Assignlocationsbtn).click({ force: true })
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.locationscheckbox).check()
    cy.xpath(this.locator.Checklist.Assignbtn).click({ force: true })
    cy.wait(2000)
})
And('User upload document for Ensure Adequate Ventilation', function () {
    cy.xpath(this.locator.Checklist.uploadbtn).click({ force: true })
    cy.wait(2000)
    cy.contains('Upload a Document').scrollIntoView().should('be.visible')
    cy.contains('File upload').scrollIntoView().should('be.visible')
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.uploadfilebtn).attachFile(this.data.Uploadfile, { force: true })
    cy.wait(2000)
    cy.get(this.locator.Checklist.chklistUploadbtn).contains('Upload').click({ multiple: true })
    cy.wait(10000)
    cy.contains('Ensure Adequate Ventilation').click({ force: true })
})
And('User Add option for Increase Outdoor Air Supply', function () {
    cy.wait(3000)
    cy.contains('Increase Outdoor Air Supply').scrollIntoView().click({ force: true })
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.checklistverification).click({ force: true })
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.Addoptionbtn).click({ force: true })
    cy.xpath(this.locator.Checklist.optionbtn).click()
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.exitoption).click()
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.Assignlocationsbtn).click({ force: true })
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.locationscheckbox).check()
    cy.xpath(this.locator.Checklist.Assignbtn).click({ force: true })
    cy.wait(2000)
})
And('User upload document for Increase Outdoor Air Supply', function () {
    cy.xpath(this.locator.Checklist.uploadbtn).click({ force: true })
    cy.wait(2000)
    cy.contains('Upload a Document').scrollIntoView().should('be.visible')
    cy.contains('File upload').scrollIntoView().should('be.visible')
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.uploadfilebtn).attachFile(this.data.Uploadfile, { force: true })
    cy.wait(2000)
    cy.get(this.locator.Checklist.chklistUploadbtn).contains('Upload').click({ multiple: true })
    cy.wait(10000)
    cy.contains('Increase Outdoor Air Supply').click({ force: true })
})
And('User Add option for Meet Thresholds for Radon', function () {
    cy.wait(3000)
    cy.contains('Meet Thresholds for Radon').scrollIntoView().click({ force: true })
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.checklistverification).click({ force: true })
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.Addoptionbtn).click({ force: true })
    cy.xpath(this.locator.Checklist.optionbtn).click()
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.exitoption).click()
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.Assignlocationsbtn).click({ force: true })
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.locationscheckbox).check()
    cy.xpath(this.locator.Checklist.Assignbtn).click({ force: true })
    cy.wait(2000)
})
And('User upload document for Meet Thresholds for Radon', function () {
    cy.xpath(this.locator.Checklist.uploadbtn).click({ force: true })
    cy.wait(2000)
    cy.contains('Upload a Document').scrollIntoView().should('be.visible')
    cy.contains('File upload').scrollIntoView().should('be.visible')
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.uploadfilebtn).attachFile(this.data.Uploadfile, { force: true })
    cy.wait(2000)
    cy.get(this.locator.Checklist.chklistUploadbtn).contains('Upload').click({ multiple: true })
    cy.wait(10000)
    cy.contains('Meet Thresholds for Radon').click({ force: true })
})
And('User Add option for Verify Water Quality Indicators', function () {
    cy.wait(3000)
    cy.contains('Verify Water Quality Indicators').scrollIntoView().click({ force: true })
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.checklistverification).click({ force: true })
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.Addoptionbtn).click({ force: true })
    cy.xpath(this.locator.Checklist.optionbtn).click()
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.exitoption).click()
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.Assignlocationsbtn).click({ force: true })
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.locationscheckbox).check()
    cy.xpath(this.locator.Checklist.Assignbtn).click({ force: true })
    cy.wait(2000)
})
And('User upload document for Verify Water Quality Indicators', function () {
    cy.xpath(this.locator.Checklist.uploadbtn).click({ force: true })
    cy.wait(2000)
    cy.contains('Upload a Document').scrollIntoView().should('be.visible')
    cy.contains('File upload').scrollIntoView().should('be.visible')
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.uploadfilebtn).attachFile(this.data.Uploadfile, { force: true })
    cy.wait(2000)
    cy.get(this.locator.Checklist.chklistUploadbtn).contains('Upload').click({ multiple: true })
    cy.wait(10000)
    cy.contains('Verify Water Quality Indicators').click({ force: true })
})
And('User Add option for Meet Chemical Thresholds', function () {
    cy.wait(3000)
    cy.contains('Meet Chemical Thresholds').scrollIntoView().click({ force: true })
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.checklistverification).click({ force: true })
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.Addoptionbtn).click({ force: true })
    cy.xpath(this.locator.Checklist.optionbtn).click()
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.exitoption).click()
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.Assignlocationsbtn).click({ force: true })
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.locationscheckbox).check()
    cy.xpath(this.locator.Checklist.Assignbtn).click({ force: true })
    cy.wait(2000)
})
And('User upload document for Meet Chemical Thresholds', function () {
    cy.xpath(this.locator.Checklist.uploadbtn).click({ force: true })
    cy.wait(2000)
    cy.contains('Upload a Document').scrollIntoView().should('be.visible')
    cy.contains('File upload').scrollIntoView().should('be.visible')
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.uploadfilebtn).attachFile(this.data.Uploadfile, { force: true })
    cy.wait(2000)
    cy.get(this.locator.Checklist.chklistUploadbtn).contains('Upload').click({ multiple: true })
    cy.wait(10000)
    cy.contains('Meet Chemical Thresholds').click({ force: true })
})
And('User Add option for Meet Thresholds for Organics and Pesticides', function () {
    cy.wait(3000)
    cy.contains('Meet Thresholds for Organics and Pesticides').scrollIntoView().click({ force: true })
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.checklistverification).click({ force: true })
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.Addoptionbtn).click({ force: true })
    cy.xpath(this.locator.Checklist.optionbtn).click()
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.exitoption).click()
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.Assignlocationsbtn).click({ force: true })
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.locationscheckbox).check()
    cy.xpath(this.locator.Checklist.Assignbtn).click({ force: true })
    cy.wait(2000)
})
And('User upload document for Meet Thresholds for Organics and Pesticides', function () {
    cy.xpath(this.locator.Checklist.uploadbtn).click({ force: true })
    cy.wait(2000)
    cy.contains('Upload a Document').scrollIntoView().should('be.visible')
    cy.contains('File upload').scrollIntoView().should('be.visible')
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.uploadfilebtn).attachFile(this.data.Uploadfile, { force: true })
    cy.wait(2000)
    cy.get(this.locator.Checklist.chklistUploadbtn).contains('Upload').click({ multiple: true })
    cy.wait(10000)
    cy.contains('Meet Thresholds for Organics and Pesticides').click({ force: true })
})
And('User Add option for Meet Thresholds for Drinking Water Taste', function () {
    cy.wait(3000)
    cy.contains('Meet Thresholds for Drinking Water Taste').scrollIntoView().click({ force: true })
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.checklistverification).click({ force: true })
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.Addoptionbtn).click({ force: true })
    cy.xpath(this.locator.Checklist.optionbtn).click()
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.exitoption).click()
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.Assignlocationsbtn).click({ force: true })
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.locationscheckbox).check()
    cy.xpath(this.locator.Checklist.Assignbtn).click({ force: true })
    cy.wait(2000)
})
And('User upload document for Meet Thresholds for Drinking Water Taste', function () {
    cy.xpath(this.locator.Checklist.uploadbtn).click({ force: true })
    cy.wait(2000)
    cy.contains('Upload a Document').scrollIntoView().should('be.visible')
    cy.contains('File upload').scrollIntoView().should('be.visible')
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.uploadfilebtn).attachFile(this.data.Uploadfile, { force: true })
    cy.wait(2000)
    cy.get(this.locator.Checklist.chklistUploadbtn).contains('Upload').click({ multiple: true })
    cy.wait(10000)
    cy.contains('Meet Thresholds for Drinking Water Taste').click({ force: true })
})
And('User Add option for Provide Visual Acuity', function () {
    cy.wait(3000)
    cy.contains('Provide Visual Acuity').scrollIntoView().click({ force: true })
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.checklistverification).click({ force: true })
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.Addoptionbtn).click({ force: true })
    cy.xpath(this.locator.Checklist.optionbtn).click()
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.exitoption).click()
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.Assignlocationsbtn).click({ force: true })
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.locationscheckbox).check()
    cy.xpath(this.locator.Checklist.Assignbtn).click({ force: true })
    cy.wait(2000)
})
And('User upload document for Provide Visual Acuity', function () {
    cy.xpath(this.locator.Checklist.uploadbtn).click({ force: true })
    cy.wait(2000)
    cy.contains('Upload a Document').scrollIntoView().should('be.visible')
    cy.contains('File upload').scrollIntoView().should('be.visible')
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.uploadfilebtn).attachFile(this.data.Uploadfile, { force: true })
    cy.wait(2000)
    cy.get(this.locator.Checklist.chklistUploadbtn).contains('Upload').click({ multiple: true })
    cy.wait(10000)
    cy.contains('Provide Visual Acuity').click({ force: true })
})
And('User Add option for Lighting for Day-Active People', function () {
    cy.wait(3000)
    cy.contains('Lighting for Day-Active People').scrollIntoView().click({ force: true })
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.checklistverification).click({ force: true })
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.Addoptionbtn).click({ force: true })
    cy.xpath(this.locator.Checklist.optionbtn).click()
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.exitoption).click()
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.Assignlocationsbtn).click({ force: true })
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.locationscheckbox).check()
    cy.xpath(this.locator.Checklist.Assignbtn).click({ force: true })
    cy.wait(2000)
})
And('User upload document for Lighting for Day-Active People', function () {
    cy.xpath(this.locator.Checklist.uploadbtn).click({ force: true })
    cy.wait(2000)
    cy.contains('Upload a Document').scrollIntoView().should('be.visible')
    cy.contains('File upload').scrollIntoView().should('be.visible')
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.uploadfilebtn).attachFile(this.data.Uploadfile, { force: true })
    cy.wait(2000)
    cy.get(this.locator.Checklist.chklistUploadbtn).contains('Upload').click({ multiple: true })
    cy.wait(10000)
    cy.contains('Lighting for Day-Active People').click({ force: true })
})
And('User Add option for Provide Acceptable Thermal Environment', function () {
    cy.wait(3000)
    cy.contains('Provide Acceptable Thermal Environment').scrollIntoView().click({ force: true })
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.checklistverification).click({ force: true })
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.Addoptionbtn).click({ force: true })
    cy.xpath(this.locator.Checklist.optionbtn).click()
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.exitoption).click()
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.Assignlocationsbtn).click({ force: true })
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.locationscheckbox).check()
    cy.xpath(this.locator.Checklist.Assignbtn).click({ force: true })
    cy.wait(2000)
})
And('User upload document for Provide Acceptable Thermal Environment', function () {
    cy.xpath(this.locator.Checklist.uploadbtn).click({ force: true })
    cy.wait(2000)
    cy.contains('Upload a Document').scrollIntoView().should('be.visible')
    cy.contains('File upload').scrollIntoView().should('be.visible')
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.uploadfilebtn).attachFile(this.data.Uploadfile, { force: true })
    cy.wait(2000)
    cy.get(this.locator.Checklist.chklistUploadbtn).contains('Upload').click({ multiple: true })
    cy.wait(10000)
    cy.contains('Provide Acceptable Thermal Environment').click({ force: true })
})
And('User Add option for Manage Relative Humidity', function () {
    cy.wait(3000)
    cy.contains('Manage Relative Humidity').scrollIntoView().click({ force: true })
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.checklistverification).click({ force: true })
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.Addoptionbtn).click({ force: true })
    cy.xpath(this.locator.Checklist.PA3optionbtn).click()
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.exitoption).click()
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.Assignlocationsbtn).click({ force: true })
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.locationscheckbox).check()
    cy.xpath(this.locator.Checklist.Assignbtn).click({ force: true })
    cy.wait(2000)
})
And('User upload document for Manage Relative Humidity', function () {
    cy.xpath(this.locator.Checklist.uploadbtn).click({ force: true })
    cy.wait(2000)
    cy.contains('Upload a Document').scrollIntoView().should('be.visible')
    cy.contains('File upload').scrollIntoView().should('be.visible')
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.uploadfilebtn).attachFile(this.data.Uploadfile, { force: true })
    cy.wait(2000)
    cy.get(this.locator.Checklist.chklistUploadbtn).contains('Upload').click({ multiple: true })
    cy.wait(10000)
    cy.contains('Manage Relative Humidity').click({ force: true })
})
And('User Add option for Limit Background Noise Levels', function () {
    cy.wait(3000)
    cy.contains('Limit Background Noise Levels').scrollIntoView().click({ force: true })
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.checklistverification).click({ force: true })
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.Addoptionbtn).click({ force: true })
    cy.xpath(this.locator.Checklist.optionbtn).click()
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.exitoption).click()
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.Assignlocationsbtn).click({ force: true })
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.locationscheckbox).check()
    cy.xpath(this.locator.Checklist.Assignbtn).click({ force: true })
    cy.wait(2000)
})
And('User upload document for Limit Background Noise Levels', function () {
    cy.xpath(this.locator.Checklist.uploadbtn).click({ force: true })
    cy.wait(2000)
    cy.contains('Upload a Document').scrollIntoView().should('be.visible')
    cy.contains('File upload').scrollIntoView().should('be.visible')
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.uploadfilebtn).attachFile(this.data.Uploadfile, { force: true })
    cy.wait(2000)
    cy.get(this.locator.Checklist.chklistUploadbtn).contains('Upload').click({ multiple: true })
    cy.wait(10000)
    cy.contains('Limit Background Noise Levels').click({ force: true })
})
And('User Add option for Achieve Sound Isolation at Walls', function () {
    cy.wait(3000)
    cy.contains('Achieve Sound Isolation at Walls').scrollIntoView().click({ force: true })
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.checklistverification).click({ force: true })
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.Addoptionbtn).click({ force: true })
    cy.xpath(this.locator.Checklist.PA3optionbtn).click()
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.exitoption).click()
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.Assignlocationsbtn).click({ force: true })
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.locationscheckbox).check()
    cy.xpath(this.locator.Checklist.Assignbtn).click({ force: true })
    cy.wait(2000)
})
And('User upload document for Achieve Sound Isolation at Walls', function () {
    cy.xpath(this.locator.Checklist.uploadbtn).click({ force: true })
    cy.wait(2000)
    cy.contains('Upload a Document').scrollIntoView().should('be.visible')
    cy.contains('File upload').scrollIntoView().should('be.visible')
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.uploadfilebtn).attachFile(this.data.Uploadfile, { force: true })
    cy.wait(2000)
    cy.get(this.locator.Checklist.chklistUploadbtn).contains('Upload').click({ multiple: true })
    cy.wait(10000)
    cy.contains('Achieve Sound Isolation at Walls').click({ force: true })
})
And('User Add option for Achieve Reverberation Time Thresholds', function () {
    cy.wait(3000)
    cy.contains('Achieve Reverberation Time Thresholds').scrollIntoView().click({ force: true })
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.checklistverification).click({ force: true })
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.Addoptionbtn).click({ force: true })
    cy.xpath(this.locator.Checklist.optionbtn).click()
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.exitoption).click()
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.Assignlocationsbtn).click({ force: true })
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.locationscheckbox).check()
    cy.xpath(this.locator.Checklist.Assignbtn).click({ force: true })
    cy.wait(2000)
})
And('User upload document for Achieve Reverberation Time Thresholds', function () {
    cy.xpath(this.locator.Checklist.uploadbtn).click({ force: true })
    cy.wait(2000)
    cy.contains('Upload a Document').scrollIntoView().should('be.visible')
    cy.contains('File upload').scrollIntoView().should('be.visible')
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.uploadfilebtn).attachFile(this.data.Uploadfile, { force: true })
    cy.wait(2000)
    cy.get(this.locator.Checklist.chklistUploadbtn).contains('Upload').click({ multiple: true })
    cy.wait(10000)
    cy.contains('Achieve Reverberation Time Thresholds').click({ force: true })
})
And('User Add option for Meet Thresholds for Impact Noise Rating', function () {
    cy.wait(3000)
    cy.contains('Meet Thresholds for Impact Noise Rating').scrollIntoView().click({ force: true })
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.checklistverification).click({ force: true })
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.Addoptionbtn).click({ force: true })
    cy.xpath(this.locator.Checklist.optionbtn).click()
    cy.wait(2000)
    cy.xpath(this.locator.Checklist.exitoption).click()
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.Assignlocationsbtn).click({ force: true })
    cy.wait(1000)
    cy.xpath(this.locator.Checklist.locationscheckbox).check()
    cy.xpath(this.locator.Checklist.Assignbtn).click({ force: true })
    cy.wait(2000)
})
And('User upload document for Meet Thresholds for Impact Noise Rating', function () {
    cy.xpath(this.locator.Checklist.uploadbtn).click({ force: true })
    cy.wait(2000)
    cy.contains('Upload a Document').scrollIntoView().should('be.visible')
    cy.contains('File upload').scrollIntoView().should('be.visible')
    cy.wait(3000)
    cy.xpath(this.locator.Checklist.uploadfilebtn).attachFile(this.data.Uploadfile, { force: true })
    cy.wait(2000)
    cy.get(this.locator.Checklist.chklistUploadbtn).contains('Upload').click({ multiple: true })
    cy.wait(10000)
    cy.contains('Meet Thresholds for Impact Noise Rating').click({ force: true })
})